FORMAT: 1A
HOST: https://www.terkan.me/api

# Terkan

Terkan API first draft.

# Data Structures

## User

+ id
+ email
+ name
+ pic

# Group Users

Users API

## User [/users/{id}]

Get a user's profile by id.

+ Parameters
    + id: 1 (required, number) - ID of the user

### Get user by id [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "id": 1,
                "name": "derebaba",
                "pic": "image_url"
            },
            "message": "success"
        }

## Logged-in user [/user]

A user can get his own details by token.

### Get user's details by token [GET]

+ Request (application/x-www-form-urlencoded)

    + Headers

                    Authorization: Bearer <access_token>

    + Attributes (User)

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "id": 60,
                "name": "derebabo",
                "email": "example@example.com",
                "password": "<hashed_password>",
                "pic": "<image_url>",
                "verified": 1,
                "email_token": "<email_token>",
                "created_at": "2018-04-17 10:14:54",
                "updated_at": "2018-04-22 18:50:15",
                "provider_id": "<string>",
                "provider": "facebook",
                "provider_name": "<facebookName>"
            },
            "message": "success"
        }

## Update user [/users/update]

Update user's details.

### Update user's name [PATCH]

+ Request (application/x-www-form-urlencoded)

        { 
            "name" : "derebabuş", 
        }

    + Headers

                Authorization: Bearer {access_token}

    + Attributes
        + name (string) - User's new name

+ Response 204

# Group Oauth

Authentication interface

## Get access token [/oauth/token]

### Get or refresh access token [POST]

+ Request Get token by credentials (application/x-www-form-urlencoded)

    + Body

                { 
                    "grant_type": "password",
                    "client_id": 8,
                    "client_secret": "<secret>",
                    "username": "<userEmail>",
                    "password": "<password>",
                }

+ Request Refresh token (application/x-www-form-urlencoded)

    + Body

                { 
                    "grant_type": "refresh_token",
                    "client_id": 8,
                    "client_secret": "<secret>",
                    "refresh_token": "<refreshToken>",
                }

+ Response 200 (application/json)

    + Body

                {
                    "token_type": "Bearer",
                    "expires_in": 1295997,
                    "access_token": "<accessToken>",
                    "refresh_token": "<refreshToken>"
                }

# Group Movies

Movies API

## Popular movies [/movies/popular]

Get movies which are currently popular

### Get popular movies [GET]

+ Response 200 (application/json)

    + Body

                {
                    "success": true,
                    "data": [
                        {
                            "vote_count": 1386,
                            "id": 337167,
                            "video": false,
                            "vote_average": 6.0999999999999996,
                            "title": "Fifty Shades Freed",
                            "popularity": 541.50172999999995,
                            "poster_path": "/jjPJ4s3DWZZvI4vw8Xfi4Vqa1Q8.jpg",
                            "original_language": "en",
                            "original_title": "Fifty Shades Freed",
                            "genre_ids": [
                                18,
                                10749
                            ],
                            "backdrop_path": "/9ywA15OAiwjSTvg3cBs9B7kOCBF.jpg",
                            "adult": false,
                            "overview": "Believing they have left behind shadowy figures from their past, newlyweds Christian and Ana fully embrace an inextricable connection and shared life of luxury. But just as she steps into her role as Mrs. Grey and he relaxes into an unfamiliar stability, new threats could jeopardize their happy ending before it even begins.",
                            "release_date": "2018-02-07"
                        },
                        {
                            "vote_count": 6966,
                            "id": 269149,
                            "video": false,
                            "vote_average": 7.7000000000000002,
                            "title": "Zootopia",
                            "popularity": 320.55776800000001,
                            "poster_path": "/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg",
                            "original_language": "en",
                            "original_title": "Zootopia",
                            "genre_ids": [
                                16,
                                12,
                                10751,
                                35
                            ],
                            "backdrop_path": "/mhdeE1yShHTaDbJVdWyTlzFvNkr.jpg",
                            "adult": false,
                            "overview": "Determined to prove herself, Officer Judy Hopps, the first bunny on Zootopia's police force, jumps at the chance to crack her first case - even if it means partnering with scam-artist fox Nick Wilde to solve the mystery.",
                            "release_date": "2016-02-11"
                        },
                        ...,
                    ],
                    "message": "success"
                }

